meta_product_name: "Jay's Cocktails"
meta_title: "Jay's Cocktails - the only way to get tipsy with style"
meta_description: "Jay's Cocktails - the only way to get tipsy with style and if you are still looking for a Junior Full Stack Developer, do not hesitate to reach out and leave a message. I am that guy you are looking for - fingers crossed!"
meta_image: "cocktail.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
